numbers = File.stream!("input/day9.txt")
          |> Stream.map(&String.trim/1)
          |> Stream.reject(fn x -> String.length(x) == 0 end)
          |> Enum.map(&String.to_integer/1)
first_invalid_number = Day9.first_invalid_number(numbers, 25)
IO.puts("First invalid number: #{first_invalid_number}")
sub_sequence = Day9.adds_up(numbers, first_invalid_number)
{min, max} = Enum.min_max(sub_sequence)
IO.puts("Encryption weakness: #{min + max}")
